### ISSUE TITLE
Using model only for bug detection

### ISSUE THREAD

**Issue by hsellik** [VHellendoorn/ICLR20-Great#1]
Hi,

Very nice reproduction package! 

I am thinking about using this model for finding bugs in binary expressions. So the task is to find the erroneous binary operator without any reference to other parts of the code. I'd compare it to the VarMisuse task without pointing to the correct variable.

Is there a nice way to modify this model for the task? I was thinking of modifying the final Dense layer to 1, so only one pointer is outputted in here: https://github.com/VHellendoorn/ICLR20-Great/blob/master/running/meta_model.py#L15.

Then change the loss function accordingly. There is probably some extra work to look at the binary expressions instead of variables as well. Haven't figured that part out yet.

Would this be a good solution?

Best Regards,
Hendrig

**Comment by VHellendoorn** [comment]
Hi Hendrig,

That's definitely a good use-case. I agree that the, let's call it "most proper", way to do this is to change the prediction tensor to a simple 1-D projection. It will also take a bit of cleaning to get rid of e.g. the candidate set and whatnot from the data loader.
If you want to get this started especially quickly though (e.g. for prototyping), you could even go as simple as zeroing out the repair loss (i.e., multiply it by zero) and just providing dummy targets for it. That will make it train with no gradients on the second pointer, which should give a quick insight into how feasible this is.

Bigger picture, I've been thinking of separating the task layer entirely to allow arbitrary input/objective pairs to be run through the model; if I find some time to do that soon, that might help for things like this down the line. That probably won't be in the next few days though, so let me know if you need some coding support on a fork and I'm happy to help make these edits.

-Vincent

**Comment by hsellik** [comment]
Hi Vincent, 

Alright, I am indeed prototyping, so this approach sounds very good. Thank you for the feedback! I might make a new issue if I get into trouble with something. 😀 

I can use the model pretty much as it is since my task is very similar. However, I have seen a lot of people working on other tasks, such as finding security vulnerabilities, and I think it would be pretty cool if people would make their model easier to use for other objectives on both node and graph level.

With that said, I think a good reproduction package, such as this, already goes a long way. 

Cheers,
Hendrig
