### ISSUE TITLE
License

### ISSUE THREAD

**Issue by egor-bogomolov** [VHellendoorn/ICLR20-Great#2]
Hello! Thanks for a great supplementary package and a clear implementation of all the models!

Could you please add a license for the repository? The default GitHub license does not allow to do *anything* with the repository, except for forking and viewing. Right now, strictly speaking, users are not even allowed to run the code or re-use it in other projects. For more details see [here](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license#:~:text=From%20GitHub's%20licensing%20help%20page,derivative%20works%20from%20your%20work.).

**Comment by VHellendoorn** [comment]
Oops, you are very right! Resolved in 2bc28f7. Thanks for point that out.

-Vincent

**Comment by egor-bogomolov** [comment]
Thanks a lot!
