### ISSUE TITLE
Hi,something about GGNN 

### ISSUE THREAD

**Issue by ross-Hr** [VHellendoorn/ICLR20-Great#8]
I want to add an attention mechanism to ggnn. Which part of the code should I modify

**Comment by ross-Hr** [comment]
Like [ keras-gat](https://github.com/danielegrattarola/keras-gat),developed by Daniele Grattarola

**Comment by VHellendoorn** [comment]
Probably best to modify the [`propagate function`](https://github.com/VHellendoorn/ICLR20-Great/blob/master/models/ggnn.py#L73). Right now, that function implements:

- summing all incoming messages per node (by edge type), and 
- combining the old state with the new ones using a GRU (line 92).

How you'd update that is up to you, but the gist for a GAT is typically that you replace "sum + GRU" with "attend". That won't be terribly trivial, but that's part of the fun :)
